import { useEffect, useMemo, useState } from 'react';
import { api } from './api';
import { formatChange, formatCurrency } from './view-model';

type Overview = { indices: any[]; watchlist: any[]; updatedAt: string };
type Noise = { groups: Record<string, any[]> };
const noiseLabels: Record<string, string> = { important: '重要信息', general: '一般信息', noise: '市场噪音', risk: '风险提示' };

export default function App() {
  const [overview, setOverview] = useState<Overview>(); const [noise, setNoise] = useState<Noise>(); const [portfolio, setPortfolio] = useState<any>();
  const [symbol, setSymbol] = useState(''); const [order, setOrder] = useState({ symbol: 'AAPL', side: 'buy', quantity: 1, reason: '' }); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const refresh = async () => { setLoading(true); try { const [o,n,p] = await Promise.all([api.overview(),api.noise(),api.portfolio()]); setOverview(o);setNoise(n);setPortfolio(p);setMessage(''); } catch(e){setMessage(e instanceof Error?e.message:'后端未连接')} finally{setLoading(false)} };
  useEffect(()=>{refresh()},[]);
  const submitOrder = async (event: React.FormEvent) => { event.preventDefault();setBusy(true);try{await api.createOrder({...order,quantity:Number(order.quantity)});setMessage('模拟订单已成交');await refresh()}catch(e){setMessage(e instanceof Error?e.message:'订单失败')}finally{setBusy(false)} };
  const addSymbol = async (event: React.FormEvent) => { event.preventDefault();if(!symbol.trim())return;setBusy(true);try{await api.addWatchlist(symbol);setSymbol('');setMessage('已加入自选股');await refresh()}catch(e){setMessage(e instanceof Error?e.message:'添加失败')}finally{setBusy(false)} };
  const pnl = useMemo(()=>portfolio?.positions?.reduce((sum:number,p:any)=>sum+p.unrealizedPnl,0)??0,[portfolio]);
  return <main className="app-shell">
    <header className="topbar"><div className="brand-lockup"><span className="brand-mark">$</span><div><p className="eyebrow">TRADING / US EQUITIES</p><h1>市场研究台<span className="cursor" aria-hidden="true">▮</span></h1></div></div><nav className="terminal-nav" aria-label="页面导航"><a href="#overview">--概览</a><a href="#noise">--噪音</a><a href="#trade">--模拟交易</a><button className="refresh-button" onClick={refresh} disabled={loading}>{loading?'同步中…':'刷新数据'}</button></nav></header>
    {message&&<div className="notice" role="status">{message}</div>}
    <section id="overview" className="hero-panel"><div><p className="section-kicker">DAILY MARKET BRIEF / 延迟演示数据</p><h2>先看今天的市场，<br/><span>再决定要不要出手。</span></h2><p className="hero-copy">把指数、市场噪音和模拟决策放在同一张桌面上。</p></div><div className="hero-status"><span className="status-dot"/>数据状态 <b>{overview?.updatedAt?'已同步':'等待连接'}</b><small>{overview?.updatedAt??'—'}</small></div></section>
    <section className="metric-grid" aria-label="核心指标"><div className="metric-card"><span className="label">组合总资产</span><strong>{formatCurrency(portfolio?.totalAssets??100000)}</strong><small>现金 {formatCurrency(portfolio?.cash??100000)} · 持仓 {formatCurrency(portfolio?.marketValue??0)}</small></div><div className="metric-card accent-card"><span className="label">今日市场</span><strong>{overview?.indices?.[1]?formatChange(overview.indices[1].changePercent):'—'}</strong><small>纳斯达克综合指数</small></div><div className="metric-card"><span className="label">未实现盈亏</span><strong className={pnl>=0?'positive':'negative'}>{formatCurrency(pnl)}</strong><small>仅用于模拟复盘</small></div></section>
    <section className="workspace-grid"><div className="main-column"><section className="panel" aria-labelledby="indices-title"><div className="panel-title"><div><span className="section-kicker">01 / MARKET PULSE</span><h2 id="indices-title">市场指数</h2></div><span className="panel-meta">{overview?.updatedAt??'加载中'}</span></div><div className="quote-grid">{overview?.indices?.map(q=><article className="quote" key={q.symbol}><span>{q.name}</span><b>{q.price.toLocaleString()}</b><em className={q.changePercent>=0?'positive':'negative'}>{formatChange(q.changePercent)}</em><div className="sparkline" aria-hidden="true"/></article>)}</div></section>
    <section className="panel" aria-labelledby="watchlist-title"><div className="panel-title"><div><span className="section-kicker">02 / YOUR TICKERS</span><h2 id="watchlist-title">自选股</h2></div><form onSubmit={addSymbol} className="inline-form"><label className="sr-only" htmlFor="watch-symbol">股票代码</label><input id="watch-symbol" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="代码"/><button disabled={busy}>添加</button></form></div><div className="watchlist">{overview?.watchlist?.map(q=><div className="watch-row" key={q.symbol}><b>{q.symbol}</b><span>{q.name}</span><strong>{formatCurrency(q.price)}</strong><em className={q.changePercent>=0?'positive':'negative'}>{formatChange(q.changePercent)}</em></div>)}</div></section>
    <section id="trade" className="panel trade-panel" aria-labelledby="trade-title"><div className="panel-title"><div><span className="section-kicker">03 / PAPER EXECUTION</span><h2 id="trade-title">模拟交易</h2></div><span className="tag">市价单 · $100K</span></div><form className="trade-form" onSubmit={submitOrder}><label>方向<select value={order.side} onChange={e=>setOrder({...order,side:e.target.value})}><option value="buy">买入</option><option value="sell">卖出</option></select></label><label>代码<input value={order.symbol} onChange={e=>setOrder({...order,symbol:e.target.value.toUpperCase()})}/></label><label>数量<input type="number" min="1" step="1" value={order.quantity} onChange={e=>setOrder({...order,quantity:Number(e.target.value)})}/></label><label className="reason-field">交易理由<input value={order.reason} onChange={e=>setOrder({...order,reason:e.target.value})} placeholder="可选：记录你的判断"/></label><button className="submit-button" type="submit" disabled={busy}>{busy?'处理中…':'提交模拟订单 →'}</button></form></section></div>
    <aside id="noise" className="panel radar" aria-labelledby="noise-title"><div className="panel-title"><div><span className="section-kicker">04 / SIGNAL VS NOISE</span><h2 id="noise-title">市场噪音雷达</h2></div><span className="tag">AI 分级</span></div><p className="muted">把今天的信息分成值得看、可以略过和需要留意。</p>{Object.entries(noiseLabels).map(([key,label])=><div className={`noise-group noise-${key}`} key={key}><h3>{label}<span>{noise?.groups?.[key]?.length??0}</span></h3>{noise?.groups?.[key]?.map((item:any)=><div className="noise-item" key={item.id}><b>{item.title}</b><small>{item.source} · 相关性 {item.relevance}/5</small></div>)}</div>)}</aside></section>
    <footer className="foot-stmt"><p>Make a call. Log the why.</p><div><span className="wordmark">TRADING / MVP</span><span>演示数据 · 不执行真实下单 · 不构成投资建议</span></div></footer>
  </main>;
}
