import { useEffect, useMemo, useState } from 'react';
import { api } from './api';
import { formatChange, formatCurrency } from './view-model';
import { signalTone } from './strategy-view';

type Overview={indices:any[];watchlist:any[];updatedAt:string;source?:string};
const decisionText=(signal:string)=>signal==='BUY CANDIDATE'?'可以考虑买入':signal==='AVOID'?'暂时不要买':'继续观察';
export default function App(){
  const [overview,setOverview]=useState<Overview>();const [noise,setNoise]=useState<any>();const [portfolio,setPortfolio]=useState<any>();const [orders,setOrders]=useState<any[]>([]);const [strategies,setStrategies]=useState<Record<string,any>>({});const [selected,setSelected]=useState('AAPL');const [order,setOrder]=useState({symbol:'AAPL',side:'buy',quantity:1,reason:''});const [symbol,setSymbol]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
  const refresh=async()=>{setLoading(true);try{const[o,n,p,history]=await Promise.all([api.overview(),api.noise(),api.portfolio(),api.orders()]);setOverview(o);setNoise(n);setPortfolio(p);setOrders(history);const pairs=await Promise.all(o.watchlist.map(async(q:any)=>{try{return[q.symbol,await api.strategy(q.symbol)]as const}catch{return[q.symbol,null]as const}}));setStrategies(Object.fromEntries(pairs));if(!o.watchlist.some((q:any)=>q.symbol===selected)&&o.watchlist[0])setSelected(o.watchlist[0].symbol);setMessage('')}catch(e){setMessage(e instanceof Error?e.message:'后端未连接')}finally{setLoading(false)}};
  useEffect(()=>{refresh();const timer=window.setInterval(refresh,30000);return()=>window.clearInterval(timer)},[]);
  const current=overview?.watchlist?.find(q=>q.symbol===selected);const strategy=strategies[selected];const pnl=useMemo(()=>portfolio?.positions?.reduce((sum:number,p:any)=>sum+p.unrealizedPnl,0)??0,[portfolio]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api.createOrder({...order,quantity:Number(order.quantity)});setMessage('模拟订单已提交');await refresh()}catch(err){setMessage(err instanceof Error?err.message:'订单失败')}finally{setBusy(false)}};
  const add=async(e:React.FormEvent)=>{e.preventDefault();if(!symbol.trim())return;setBusy(true);try{await api.addWatchlist(symbol);setSymbol('');setMessage('已加入自选股');await refresh()}catch(err){setMessage(err instanceof Error?err.message:'添加失败')}finally{setBusy(false)}};
  return <main className="simple-app"><header className="simple-header"><div><p className="eyebrow">TRADING / 美股研究</p><h1>市场研究台</h1></div><div className="header-status"><span className="status-dot"/>{overview?.source==='yahoo-latest'?'最新报价':'演示数据'}<small>{overview?.updatedAt??'—'}</small></div><button onClick={refresh} disabled={loading}>{loading?'更新中…':'刷新'}</button></header>{message&&<div className="notice" role="status">{message}</div>}
    <section className="market-strip"><div><span>标普 500</span><b>{overview?.indices?.[0]?.price?.toLocaleString()??'—'}</b><em className={overview?.indices?.[0]?.changePercent>=0?'positive':'negative'}>{overview?.indices?.[0]?formatChange(overview.indices[0].changePercent):'—'}</em></div><div><span>纳斯达克</span><b>{overview?.indices?.[1]?.price?.toLocaleString()??'—'}</b><em className={overview?.indices?.[1]?.changePercent>=0?'positive':'negative'}>{overview?.indices?.[1]?formatChange(overview.indices[1].changePercent):'—'}</em></div><div><span>账户总资产</span><b>{formatCurrency(portfolio?.totalAssets??100000)}</b><em className={pnl>=0?'positive':'negative'}>浮动盈亏 {formatCurrency(pnl)}</em></div></section>
    <section className="account-strip"><div><span>可用现金</span><b>{formatCurrency(portfolio?.cash??100000)}</b><small>下单后会即时变化</small></div><div><span>持仓市值</span><b>{formatCurrency(portfolio?.marketValue??0)}</b><small>{portfolio?.positions?.length??0} 个持仓</small></div><div><span>已实现收益</span><b className={(portfolio?.realizedPnl??0)>=0?'positive':'negative'}>{formatCurrency(portfolio?.realizedPnl??0)}</b><small>卖出后结算</small></div></section>
    <div className="simple-grid"><aside className="panel watch-panel"><div className="panel-heading"><div><span className="kicker">我的股票</span><h2>自选股</h2></div><form onSubmit={add}><label className="sr-only" htmlFor="new-symbol">股票代码</label><input id="new-symbol" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="代码"/><button disabled={busy}>添加</button></form></div><div className="watch-items">{overview?.watchlist?.map(q=><button className={`watch-item ${q.symbol===selected?'selected':''}`} key={q.symbol} onClick={()=>{setSelected(q.symbol);setOrder({...order,symbol:q.symbol})}}><b>{q.symbol}</b><span>{q.name}</span><strong>{formatCurrency(q.price)}</strong><em className={q.changePercent>=0?'positive':'negative'}>{formatChange(q.changePercent)}</em></button>)}</div></aside>
    <section className="panel analysis-panel"><div className="panel-heading"><div><span className="kicker">股票分析</span><h2>{selected} <small>{current?.name}</small></h2></div><span className="data-time">{current?.updatedAt??'—'}</span></div>{current&&<div className="quote-hero"><strong>{formatCurrency(current.price)}</strong><em className={current.changePercent>=0?'positive':'negative'}>{formatChange(current.changePercent)}</em></div>}{strategy?<><div className={`decision ${signalTone(strategy.signal)}`}><span>当前判断</span><strong>{decisionText(strategy.signal)}</strong><small>评分 {strategy.score}/100 · 市场状态 {strategy.regime}</small></div><div className="reason-columns"><div><h3>支持因素</h3>{strategy.evidence.supporting.slice(0,3).map((x:string)=><p key={x}>✓ {x}</p>)}</div><div><h3>风险因素</h3>{strategy.evidence.opposing.slice(0,3).map((x:string)=><p key={x}>! {x}</p>)}</div></div>{strategy.plan&&<div className="plan-row"><span>入场 {strategy.plan.entry.toFixed(2)}</span><span>止损 {strategy.plan.stopLoss.toFixed(2)}</span><span>目标 {strategy.plan.takeProfit.toFixed(2)}</span></div>}</>:<div className="empty-state">暂无足够历史数据，至少需要 60 根日线。</div>}</section>
    <aside className="panel action-panel"><div className="panel-heading"><div><span className="kicker">模拟交易</span><h2>做一个选择</h2></div><span className="paper-badge">虚拟账户</span></div><div className="action-buttons"><button className={order.side==='buy'?'active':''} onClick={()=>setOrder({...order,side:'buy'})}>模拟买入</button><button className={order.side==='sell'?'active':''} onClick={()=>setOrder({...order,side:'sell'})}>模拟卖出</button></div><form className="order-form" onSubmit={submit}><label>股票<input value={order.symbol} onChange={e=>setOrder({...order,symbol:e.target.value.toUpperCase()})}/></label><label>数量<input type="number" min="1" value={order.quantity} onChange={e=>setOrder({...order,quantity:Number(e.target.value)})}/></label><label>理由<textarea value={order.reason} onChange={e=>setOrder({...order,reason:e.target.value})} placeholder="为什么做这个选择？"/></label><button className="primary-action" disabled={busy}>{busy?'处理中…':'提交模拟订单'}</button></form></aside></div>
    <section className="panel account-panel"><div className="panel-heading"><div><span className="kicker">账户记录</span><h2>我的持仓</h2></div><span className="data-time">实时按最新报价估值</span></div>{portfolio?.positions?.length?<div className="position-list">{portfolio.positions.map((p:any)=><div className="position-line" key={p.symbol}><b>{p.symbol}</b><span>{p.quantity} 股 · 成本 {formatCurrency(p.averageCost)}</span><strong>{formatCurrency(p.marketValue)}</strong><em className={p.unrealizedPnl>=0?'positive':'negative'}>{formatCurrency(p.unrealizedPnl)}</em></div>)}</div>:<div className="empty-state">还没有持仓。提交一笔模拟买入后，会在这里看到市值和浮动盈亏。</div>}</section>
    <section className="panel orders-panel"><div className="panel-heading"><div><span className="kicker">交易记录</span><h2>最近操作</h2></div></div>{orders.length?<div className="order-list">{orders.slice(0,5).map((o:any)=><div className="order-line" key={o.id}><b className={o.side==='buy'?'positive':'negative'}>{o.side==='buy'?'买入':'卖出'} {o.symbol}</b><span>{o.quantity} 股 × {formatCurrency(o.price)}</span><small>{new Date(o.createdAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></div>)}</div>:<div className="empty-state">还没有交易记录。</div>}</section>
    <section className="panel noise-panel"><div className="panel-heading"><div><span className="kicker">市场信息</span><h2>今天需要注意什么</h2></div><span className="data-time">{noise?.updatedAt??'—'}</span></div><div className="noise-list">{['important','general','noise','risk'].flatMap(k=>(noise?.groups?.[k]??[]).slice(0,2)).map((item:any)=><div className="noise-line" key={item.id}><b>{item.title}</b><span>{item.source} · 可信度 {item.credibility}/5</span></div>)}</div></section><footer>历史数据来自 Yahoo Finance · 最新报价可能有延迟 · 仅用于模拟研究，不构成投资建议</footer></main>}
