import { useEffect, useMemo, useState } from 'react';
import { api } from './api';
import { formatChange, formatCurrency } from './view-model';
import { signalTone } from './strategy-view';

type Overview = { indices: any[]; watchlist: any[]; updatedAt: string; source?: string };
type Noise = { groups: Record<string, any[]> };
const labels: Record<string, string> = { important: '重要情报', general: '一般情报', noise: '市场陷阱', risk: '风险警报' };

export default function App() {
  const [overview, setOverview] = useState<Overview>(); const [noise, setNoise] = useState<Noise>(); const [portfolio, setPortfolio] = useState<any>(); const [strategies, setStrategies] = useState<Record<string, any>>({});
  const [order, setOrder] = useState({ symbol: 'AAPL', side: 'buy', quantity: 1, reason: '' }); const [symbol, setSymbol] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const refresh = async () => { setLoading(true); try { const [o,n,p]=await Promise.all([api.overview(),api.noise(),api.portfolio()]); setOverview(o);setNoise(n);setPortfolio(p); const pairs=await Promise.all(o.watchlist.map(async(q:any)=>{try{return [q.symbol,await api.strategy(q.symbol)] as const}catch{return [q.symbol,null] as const}})); setStrategies(Object.fromEntries(pairs));setMessage(''); } catch(e){setMessage(e instanceof Error?e.message:'后端未连接')} finally{setLoading(false)} };
  useEffect(()=>{refresh();const timer=window.setInterval(refresh,30000);return()=>window.clearInterval(timer)},[]);
  const pnl=useMemo(()=>portfolio?.positions?.reduce((sum:number,p:any)=>sum+p.unrealizedPnl,0)??0,[portfolio]);
  const submitOrder=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api.createOrder({...order,quantity:Number(order.quantity)});setMessage('任务完成：模拟订单已成交');await refresh()}catch(err){setMessage(err instanceof Error?err.message:'订单失败')}finally{setBusy(false)}};
  const addSymbol=async(e:React.FormEvent)=>{e.preventDefault();if(!symbol.trim())return;setBusy(true);try{await api.addWatchlist(symbol);setSymbol('');setMessage('新角色已加入市场地图');await refresh()}catch(err){setMessage(err instanceof Error?err.message:'添加失败')}finally{setBusy(false)}};
  return <main className="game-shell">
    <header className="game-topbar"><div className="game-brand"><span className="pixel-avatar">$</span><div><p className="eyebrow">TRADING QUEST / SEASON 01</p><h1>市场冒险家<span className="cursor">▮</span></h1></div></div><div className="player-card"><span>PLAYER 01</span><b>LV. 03</b><div className="xp-bar"><i style={{width:'68%'}} /></div><small>680 / 1000 XP</small></div><button className="refresh-button" onClick={refresh} disabled={loading}>{loading?'同步中…':'刷新世界'}</button></header>
    {message&&<div className="notice" role="status">{message}</div>}
    <section className="game-hero"><div><p className="section-kicker">MISSION 01 / DAILY MARKET</p><h2>今天的市场<br/><span>会给你什么任务？</span></h2><p>探索指数世界，识别噪音陷阱，用虚拟资金完成一次有理由的行动。</p></div><div className="world-status"><span className="status-dot"/><b>{overview?.source==='yahoo-latest'?'LIVE-LITE':'DEMO WORLD'}</b><small>{overview?.updatedAt??'等待世界加载'}</small></div></section>
    <section className="quest-row"><div className="quest-card active"><span className="quest-icon">★</span><div><b>今日任务</b><strong>找到一个可解释的突破</strong><small>完成一次 BUY / WATCH 决策</small></div><em>0/1</em></div><div className="quest-card"><span className="quest-icon">◆</span><div><b>连胜奖励</b><strong>连续 3 次记录交易理由</strong><small>解锁：决策日志徽章</small></div><em>1/3</em></div><div className="streak"><small>当前连胜</small><strong>02</strong><span>天</span></div></section>
    <section className="metric-grid" aria-label="玩家状态"><div className="metric-card"><span className="label">资产能量</span><strong>{formatCurrency(portfolio?.totalAssets??100000)}</strong><small>可用现金 {formatCurrency(portfolio?.cash??100000)}</small></div><div className="metric-card accent-card"><span className="label">世界情绪</span><strong>{overview?.indices?.[1]?formatChange(overview.indices[1].changePercent):'—'}</strong><small>NASDAQ · {overview?.source==='yahoo-latest'?'最新报价':'演示快照'}</small></div><div className="metric-card"><span className="label">战斗收益</span><strong className={pnl>=0?'positive':'negative'}>{formatCurrency(pnl)}</strong><small>模拟复盘得分</small></div></section>
    <section className="game-grid"><div className="main-column"><section className="panel map-panel"><div className="panel-title"><div><span className="section-kicker">WORLD MAP / INDEX ZONE</span><h2>市场世界</h2></div><span className="tag">{overview?.source==='yahoo-latest'?'LIVE-LITE':'DEMO'}</span></div><div className="index-world">{overview?.indices?.map(q=><article className="world-node" key={q.symbol}><div className="node-orbit"><span>{q.symbol}</span></div><b>{q.name}</b><strong>{q.price.toLocaleString()}</strong><em className={q.changePercent>=0?'positive':'negative'}>{formatChange(q.changePercent)}</em><small>探索等级 {q.changePercent>=0?'↑':'↓'}</small></article>)}</div></section>
    <section className="panel"><div className="panel-title"><div><span className="section-kicker">CHARACTER ROSTER / YOUR TICKERS</span><h2>股票角色</h2></div><form onSubmit={addSymbol} className="inline-form"><label className="sr-only" htmlFor="watch-symbol">股票代码</label><input id="watch-symbol" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="召唤代码"/><button disabled={busy}>召唤</button></form></div><div className="watchlist">{overview?.watchlist?.map(q=><div className="character-row" key={q.symbol}><span className="character-avatar">{q.symbol.slice(0,1)}</span><b>{q.symbol}</b><span>{q.name}</span><strong>{formatCurrency(q.price)}</strong><em className={q.changePercent>=0?'positive':'negative'}>{formatChange(q.changePercent)}</em><span className="character-hp"><i style={{width:`${Math.min(100,Math.abs(q.changePercent)*20+40)}%`}} /></span></div>)}</div></section>
    <section className="panel trade-panel" id="trade"><div className="panel-title"><div><span className="section-kicker">ACTION MENU / PAPER BATTLE</span><h2>行动面板</h2></div><span className="tag">虚拟资金 $100K</span></div><form className="trade-form" onSubmit={submitOrder}><label>动作<select value={order.side} onChange={e=>setOrder({...order,side:e.target.value})}><option value="buy">BUY / 买入</option><option value="sell">SELL / 卖出</option></select></label><label>角色<input value={order.symbol} onChange={e=>setOrder({...order,symbol:e.target.value.toUpperCase()})}/></label><label>数量<input type="number" min="1" value={order.quantity} onChange={e=>setOrder({...order,quantity:Number(e.target.value)})}/></label><label className="reason-field">行动理由<input value={order.reason} onChange={e=>setOrder({...order,reason:e.target.value})} placeholder="写下你的判断，获得 XP"/></label><button className="submit-button" disabled={busy}>{busy?'执行中…':'执行行动 →'}</button></form></section></div>
    <aside className="panel radar"><div className="panel-title"><div><span className="section-kicker">ENEMY LOG / SIGNAL VS NOISE</span><h2>噪音敌人</h2></div><span className="tag">AI 分级</span></div><p className="muted">不是所有情报都值得消耗你的注意力。</p>{Object.entries(labels).map(([key,label])=><div className={`noise-group noise-${key}`} key={key}><h3>{label}<span>{noise?.groups?.[key]?.length??0}</span></h3>{noise?.groups?.[key]?.map((item:any)=><div className="noise-item" key={item.id}><b>{item.title}</b><small>{item.source} · 可信度 {item.credibility}/5</small></div>)}</div>)}</aside></section>
    <section className="panel strategy-panel"><div className="panel-title"><div><span className="section-kicker">SKILL TREE / DECISION ENGINE</span><h2>策略技能树</h2></div><span className="tag">解锁中的技能</span></div><div className="skill-tree"><div className="skill unlocked"><b>01</b><strong>趋势侦察</strong><small>EMA20 / EMA50</small></div><span>→</span><div className="skill unlocked"><b>02</b><strong>突破识别</strong><small>20 日高点</small></div><span>→</span><div className="skill"><b>03</b><strong>风险护盾</strong><small>ATR 止损 · 2R 目标</small></div></div>{overview?.watchlist?.slice(0,3).map(q=>{const s=strategies[q.symbol];return <div className="signal-line" key={q.symbol}><b>{q.symbol}</b><span className={s?signalTone(s.signal):'muted'}>{s?.signal??'等待历史数据'}</span><small>{s?.regime??'—'} · {s?.plan?`止损 ${s.plan.stopLoss} / 目标 ${s.plan.takeProfit}`:'至少需要 60 根日线'}</small></div>})}</section>
    <footer className="game-footer"><strong>Every trade is a story.</strong><span>TRADING QUEST · 模拟世界 · 不构成投资建议</span></footer>
  </main>;
}
